### PR TITLE
Custom Scorer for CV inside plot_learning_curve

### PR DESCRIPTION
**Pull request by jengelman**
Issue: #26

Added scoring parameter to plot_learning_curve, which passes to the scikit-learn learning_curve function.

### CODE REVIEW

**Comment by reiinakano** [comment]
Hi @jengelman, thanks for this! Could you add a simple unit test simply to see if the new argument runs with no errors?

**Comment by jengelman** [comment]
@reiinakano Sure!  Wasn't sure if one was necessary since the classifier and regressor unit tests already cover plot_learning_curve, calling it with default params.  Can I just add a test for a single non-accuracy (in the classifier tests) and r2 (for the regressor tests) or do you want something more in depth?

**Comment by reiinakano** [comment]
No need for anything in-depth, what you mentioned is perfectly fine!

**Comment by reiinakano** [comment]
Merged as I want this as part of a bigger change in v0.3.0

**Comment by jengelman** [comment]
Sorry for the delay on those tests, excited for the new version!

**Pull request merged**
